Vagrant.configure("2") do |config|

  config.vm.box = "almalinux/8"
  config.vm.hostname = "app01"
  config.vm.network "private_network", ip: "192.169.1.3"
  config.vm.provision "shell", path: "provision.sh"

end