Vagrant.configure("2") do |config|
  config.vm.box = "almalinux/8"

  config.vbguest.auto_update = false

  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Trocado de rsync para virtualbox
  config.vm.synced_folder "./html", "/var/www/html",
    type: "virtualbox"

  config.vm.provision "shell", inline: <<-SHELL
    echo "nameserver 8.8.8.8" > /etc/resolv.conf
    echo "nameserver 1.1.1.1" >> /etc/resolv.conf
  SHELL

  config.vm.provision "shell", path: "provision.sh"
end